### ISSUE TITLE
Add ARM GPU support 

### ISSUE THREAD

**Issue by GH-Jo** [SKKU-ESLAB/CNN-on-flash#1]
Currently, on-flash gemm only support ARM CPU. 

GPU support is needed for usage in various environments and performance comparison between processors.

**Comment by LeeHayun** [comment]
The current direction of research is mainly NAS that finds a deep learning model suitable for a given memory size rather than using less memory.

Therefore, it is more valuable to train a model for the GPU and generate an optimized GPU kernel than to apply the technique to the GPU.
These works are in progress in the following repositories.
https://github.com/SKKU-ESLAB/ANT-Model-DB
https://github.com/SKKU-ESLAB/Auto-Compression

So, I close this issue.
