### ISSUE TITLE
Need partial im2col operation

### ISSUE THREAD

**Issue by GH-Jo** [SKKU-ESLAB/CNN-on-flash#2]
We need to add partial im2col operation.

It is necessary to operate im2col on input tensor for convolution using gemm. 
im2col should be done while a partial matrix is in memory and the other parts are in storage.

**Comment by LeeHayun** [comment]
The current direction of research is mainly NAS that finds a deep learning model suitable for a given memory size rather than using less memory.

Therefore, it is more valuable to train a model for the GPU and generate an optimized GPU kernel than to apply the technique to the GPU.
These works are in progress in the following repositories.
https://github.com/SKKU-ESLAB/ANT-Model-DB
https://github.com/SKKU-ESLAB/Auto-Compression

So, I close this issue.
