### ISSUE TITLE
Expand the coverage of the memory budget

### ISSUE THREAD

**Issue by GH-Jo** [SKKU-ESLAB/CNN-on-flash#3]
Now the memory budget only includes submatrices allocated on memory.
For more general usage, it is necessary to include total memory usage of the process that executes gemm in the memory budget.

**Comment by LeeHayun** [comment]
The current direction of research is mainly NAS that finds a deep learning model suitable for a given memory size rather than using less memory.

Therefore, it is more valuable to train a model for the GPU and generate an optimized GPU kernel than to apply the technique to the GPU.
These works are in progress in the following repositories.
https://github.com/SKKU-ESLAB/ANT-Model-DB
https://github.com/SKKU-ESLAB/Auto-Compression

So, I close this issue.
