### ISSUE TITLE
Partial reshape operation

### ISSUE THREAD

**Issue by GH-Jo** [SKKU-ESLAB/CNN-on-flash#4]
Convolution implementation using gemm needs weight filters of a convolutional layer to be reshaped.
To reduce the maximum memory usage, reshape procedure should progress while partial matrices are loaded from storage and reshaped sequentially, not the whole matrix loaded at the same time.
		
So I propose to make partial reshape operation.

**Comment by LeeHayun** [comment]
The current direction of research is mainly NAS that finds a deep learning model suitable for a given memory size rather than using less memory.

Therefore, it is more valuable to train a model for the GPU and generate an optimized GPU kernel than to apply the technique to the GPU.
These works are in progress in the following repositories.
https://github.com/SKKU-ESLAB/ANT-Model-DB
https://github.com/SKKU-ESLAB/Auto-Compression

So, I close this issue.
