### ISSUE TITLE
Introducing CNN-on-flash to ArmCL's layers

### ISSUE THREAD

**Issue by RedCarrottt** [SKKU-ESLAB/CNN-on-flash#6]
CNN-on-flash seems to support only GEMM operators.

However, real machine learning apps usually use layer-wise operators; such as convolution layer, fully-connected layer.

If you want to apply it to convolution layer, supporting for im2col is imperative.

**Comment by LeeHayun** [comment]
The current direction of research is mainly NAS that finds a deep learning model suitable for a given memory size rather than using less memory.

Therefore, it is more valuable to train a model for the GPU and generate an optimized GPU kernel than to apply the technique to the GPU.
These works are in progress in the following repositories.
https://github.com/SKKU-ESLAB/ANT-Model-DB
https://github.com/SKKU-ESLAB/Auto-Compression

So, I close this issue.
